const statusCodes = [
  {
    "status": 100,
    "legenda": "Continue",
    "imagem": "status100",
    "descricao": "Indica que até o momento tudo está OK e que o cliente pode continuar com a requisição ou ignorar caso já tenha terminado.",
    "adicional": "Para ter uma verificação pelo servidor o cliente deve enviar o header Expect: 100-continue na requisição inicial e receber o status 100 Continue antes de enviar o body da requisição.",
  },
  {
    "status": 101,
    "legenda": "Switching Protocols",
    "imagem": "status101",
    "descricao": "Indica para qual protocolo o servidor está trocando, conforme solicitado por um cliente que tenha enviado uma mensagem incluindo Upgrade no cabeçalho da requisição. O servidor inclui Upgrade no seu cabeçalho de resposta para indicar para qual protocolo o cliente foi redirecionado.",
    "adicional": "Presume-se que o servidor só concordará em alternar protocolos quando for vantajoso fazê-lo. Por exemplo, mudar para uma versão mais recente de HTTP pode ser vantajoso em relação às versões mais antigas, e mudar para um protocolo síncrono em tempo real pode ser vantajoso ao fornecer recursos que usam tais recursos.",
  },
  {
    "status": 103,
    "legenda": "Early Hints",
    "imagem": "status103",
    "descricao": "É destinado principalmente a ser usado com o cabeçalho link para permitir ao agente do usuário começar pré-carregamento de recursos enquanto o servidor ainda está preparando uma resposta.",
  },
  {
    "status": 200,
    "legenda": "OK",
    "imagem": "status200",
    "descricao": "Indica que a requisição foi bem sucedida. Uma resposta 200 é cacheável por padrão.",
    "adicional": "O resultado de sucesso de um PUT ou DELETE geralmente não são 200 OK, e sim 204 No Content (ou 201 Created quando o recurso é carregado pela primeira vez). O significado de sucesso depende do método de requisição HTTP: GET (recurso foi carregado e transmitido no corpo da mensagem), HEAD (cabeçalhos da entidade estão no corpo da mensagem), POST (recurso descrevendo o resultado da ação está no corpo da mensagem), TRACE (corpo da mensagem contém a mensagem da requisição tal qual foi recebida pelo servidor).",
  },
  {
    "status": 201,
    "legenda": "Created",
    "imagem": "status201",
    "descricao": "É utilizado como resposta de sucesso, indica que a requisição foi bem sucedida e que um novo recurso foi criado. Este novo recurso é efetivamente criado antes do retorno da resposta e o novo recurso é enviado no corpo da mensagem (pode vir na URL ou na header Location).",
    "adicional": "Comumente, este status é utilizado em requisições do tipo POST.",
  },
  {
    "status": 202,
    "legenda": "Accepted",
    "imagem": "status202",
    "descricao": "Indica que a requisição foi recebida, mas não pode atuar ainda. Ela é sem compromisso, significando que não há maneira de o HTTP enviar posteriormente uma resposta assíncrona indicando a saída do processamento da requisição. A intenção desta resposta é para os casos onde outro processo ou, ainda, servidor lida com a requisição ou para processamentos batch.",
    "adicional": "A resposta 202 é intencionalmente evasiva. Seu objetivo é permitir que um servidor aceite uma solicitação para algum outro processo (talvez um processo orientado a lote que é executado apenas uma vez por dia) sem exigir que a conexão do agente do usuário com o servidor persista até que o processo seja concluído.",
  },
  {
    "status": 203,
    "legenda": "Non-Authoritative Information",
    "imagem": "status203",
    "descricao": "A requisição foi realizada com sucesso porém o conteúdo foi modificado por um proxy da resposta com status 200 (OK) do servidor de origem. A resposta 203 é similar a resposta com cabeçalho de Warning 214 (depreciado), significando Transformação Aplicada, o qual tem uma vantagem adicional que pode ser aplicado a respostas com qualquer código de status.",
    "adicional": "Permite que o proxy notifique os destinatários quando uma transformação foi aplicada, uma vez que esse conhecimento pode impactar decisões posteriores sobre o conteúdo. Por exemplo, solicitações futuras de validação de cache para o conteúdo podem ser aplicáveis apenas ao longo do mesmo caminho de solicitação (por meio dos mesmos proxies).",
  },
  {
    "status": 204,
    "legenda": "No Content",
    "imagem": "status204",
    "descricao": "O servidor atendeu à solicitação com êxito e não há conteúdo adicional a ser enviado na resposta. Os metadados nos campos do cabeçalho da resposta referem-se ao recurso de destino e sua representação selecionada após a aplicação da ação solicitada.",
    "adicional": "O caso de uso comum é retornar 204 como resultado de uma solicitação PUT, atualizando um recurso, sem alterar o conteúdo atual da página exibida para o usuário. Se o recurso for criado, 201 Created será retornado. Se a página for alterada para a página recém-atualizada, o 200 deve ser usado em vez disso.",
  },
  {
    "status": 205,
    "legenda": "Reset Content",
    "imagem": "status205",
    "descricao": "A requisição foi bem-sucedida, mas informa ao cliente para reconfigurar a visualização do documento, para, por exemplo, limpar o conteúdo de um formulário, redefinir um estado da tela ou atualizar a interface do usuário.",
  },
  {
    "status": 206,
    "legenda": "Partial Content",
    "imagem": "status206",
    "descricao": "A requisição teve sucesso e o corpo contém a sequência (em bytes) dos dados, como descrito no cabeçalho Range da requisição. Se existe somente uma sequência, o Content-Type de toda a resposta é colocado para o tipo do documento, e o cabeçalho Content-Range é provido. Se várias sequências são mandadas como resposta, o Content-Type é colocado para multipart/byteranges e cada fragmento cobre uma sequência, com Content-Range e Content-Type descrevendo-os.",
  },
  {
    "status": 207,
    "legenda": "Multi-Status",
    "imagem": "status207",
    "descricao": "Indica uma mistura de respostas. Esta resposta é usada exclusivamente no contexto da Web Distributed Authoring e Versioning (WebDAV). O corpo de resposta é a text/xml ou application/xml.",
    "adicional": "Os navegadores que acessam páginas da web nunca encontrarão esse código de status. A capacidade de retornar uma coleção de recursos faz parte do protocolo WebDAV e só é encontrada por aplicativos da Web que acessam um servidor WebDAV.",
  },
  {
    "status": 208,
    "legenda": "Already Reported",
    "imagem": "status208",
    "descricao": "Usado dentro de um elemento de resposta DAV: propstat para evitar enumerar os membros internos de várias ligações para a mesma coleção repetidamente. Para cada associação a uma coleção dentro do escopo da solicitação, apenas uma será relatada com um status 200, enquanto os elementos DAV:response subsequentes para todas as outras associações usarão o status 208 e nenhum elemento DAV:response para seus descendentes será incluído.",
    "adicional": "Observe que o status 208 só ocorrerá para solicitações 'Depth: infinity' e que é de particular importância quando as várias ligações de coleção causam um loop de ligação.",
  },
  {
    "status": 226,
    "legenda": "IM Used",
    "imagem": "status226",
    "descricao": "O servidor atendeu a uma solicitação GET para o recurso e a resposta é uma representação do resultado de uma ou mais manipulações de instância aplicadas à instância atual. A instância atual real pode não estar disponível, exceto pela combinação desta resposta com outras respostas anteriores ou futuras, conforme apropriado para a(s) manipulação(ões) de instância específica(s). Se assim for, os cabeçalhos da instância resultante são o resultado da combinação dos cabeçalhos da resposta 226 e das outras instâncias.",
  },
  {
    "status": 300,
    "legenda": "Multiple Choices",
    "imagem": "status300",
    "descricao": "Indica que a requisição tem uma ou mais possíveis respostas. O agente de usuário ou o usuário devem escolher uma delas. Como não há forma padrão de se escolher uma das respostas, esse código de resposta é raramente usado.",
  },
  {
    "status": 301,
    "legenda": "Moved Permanently",
    "imagem": "status301",
    "descricao": "Indica que o recurso requisitado foi movido permanentemente para a URL informada no Location header.",
    "adicional": "É recomendado que se use o código 301 somente como resposta para os métodos GET ou Head e use 308 Permanent Redirect para POST, para proibir explicitamente o uso do método com esse status."
  },
  {
    "status": 302,
    "legenda": "Found",
    "imagem": "status302",
    "descricao": "Indica que o recurso foi temporariamente movido para a URL informada no Location header. Os navegadores redirecionam para essa página porém os motores de busca não atualizam o link inicial.",
    "adicional": "É recomendado habilitar o código 302 somente em resposta aos métodos GET ou HEAD e utilizar o método 307 Temporary Redirect em outros casos, já que a troca de método é expressamente proibida nesse caso. Em casos onde você deseja que o método utilizado altere para GET, utilize 303 See Other. Isto é útil quando você deseja dar uma resposta a um método PUT que não seja um recurso, mas uma mensagem de confirmação, como por exemplo: 'você enviou XYZ com sucesso'."
  },
  {
    "status": 303,
    "legenda": "See Other",
    "imagem": "status303",
    "descricao": "Indica que o navegador deve ser redirecionado para o URL do Location header em vez de renderizar o recurso solicitado. Este código de resposta normalmente é retornado como resultado de um PUT ou POST. O método usado para mostrar esta página redirecionada é sempre GET.",
  },
  {
    "status": 304,
    "legenda": "Not Modified",
    "imagem": "status304",
    "descricao": "Indica que não há necessidade de retransmitir a requisição de recursos. É um redirecionamento implícito para o recurso em cache. Isto ocorre quando o método de requisição é safe, assim como uma requisição GET ou HEAD, ou quando a requisição é condicional e usa um cabeçalho If-None-Match ou If-Modified-Since. A resposta equivalente 200 OK teria incluso os cabeçalhos Cache-Control, Content-Location, Date, ETag, Expires, e Vary.",
  },
  {
    "status": 307,
    "legenda": "Temporary Redirect",
    "imagem": "status307",
    "descricao": "Indica que o recurso da requisição foi temporariamente alterado para a URL informada no Location header. O método e o corpo da requisição original são reutilizados para realizar a requisição de redirecionamento. Em casos onde você deseja que o método utilizado seja alterado para GET, utilize o código de estado 303 See Other. Isto é util quando você deseja dar uma resposta a um método PUT que não seja o recurso enviado, mas uma mensagem de confirmação (como por exemplo 'Envio de XYZ concluído com sucesso').",
    "adicional": "A única diferença entre 307 e 302 é que o 307 garante que o método e o corpo não são alterados quando o redirecionamento é feito. Com o 302, alguns clientes antigos alteram o método de solicitação de POST para GET.",
  },
  {
    "status": 308,
    "legenda": "Permanent Redirect",
    "imagem": "status308",
    "descricao": "Indica que o recurso solicitado foi movido permanentemente para o URL dado pelo Location header. Este código de status é semelhante a 301 Moved Permanently, exceto que não permite alterar o método de solicitação de POST para GET.",
    "adicional": "Algumas aplicações Web podem usar o 308 Permanent Redirect de forma não convencional e para outros propósitos. Por exemplo, Google Drive usa a resposta 308 Resume Incomplete para indicar ao cliente quando um upload incompleto parou.",
  },
  {
    "status": 400,
    "legenda": "Bad Request",
    "imagem": "status400",
    "descricao": "Indica que o servidor não pode ou não irá processar a requisição devido a alguma coisa que foi entendida como um erro do cliente (por exemplo, sintaxe de requisição mal formada, enquadramento de mensagem de requisição inválida ou requisição de roteamento enganosa).",
    "adicional": "Aviso: O cliente não deve repetir essa requisição sem modificá-la.",
  },
  {
    "status": 401,
    "legenda": "Unauthorized",
    "imagem": "status401",
    "descricao": "Indica que a solicitação não foi aplicada porque não possui credenciais de autenticação válidas para o recurso de destino. Esse status é enviado com um cabeçalho WWW-Authenticate que contém informações sobre como autorizar corretamente.",
    "adicional": "É semelhante a 403, mas neste caso, a autenticação é possível.",
  },
  {
    "status": 402,
    "legenda": "Payment Required",
    "imagem": "status402",
    "descricao": "É um termo despadronizado para respostas de Status, podendo-se ter usos futuros. Às vezes, este comando indica que o processo não pôde ser realizado em função de um pagamento não realizado. Originalmente, foi criado para validar uma micro ou grande transação e pode indicar que o método não se realiza até que o cliente efetue o pagamento. Contudo, não existem usos convecionais fixos e sua inserção varia, dependendo do contexto que é posto.",
    "adicional": "Esta é uma tecnologia experimental, verifique a tabela de compatibilidade entre navegadores cuidadosamente antes de usar essa funcionalidade em produção."
  },
  {
    "status": 403,
    "legenda": "Forbidden",
    "imagem": "status403",
    "descricao": "Indica que o servidor entendeu o pedido, mas se recusa a autorizá-lo. Esse status é semelhante ao 401 , mas neste caso, a re-autenticação não fará diferença. O acesso é permanentemente proibido e vinculado à lógica da aplicação (como uma senha incorreta).",
    "adicional": "Um servidor de origem que deseja 'ocultar' a existência atual de um recurso de destino proibido PODE responder com um código de status 404 Not Found.",
  },
  {
    "status": 404,
    "legenda": "Not Found",
    "imagem": "status404",
    "descricao": "Indica que o servidor não conseguiu encontrar o recurso solicitado. Normalmente, links que levam para uma página 404 estão quebrados ou desativados (link rot). Um código 404 não indica se o recurso está indisponível temporariamente ou se o recurso foi permanentemente removido. Mas, se esse for o caso, o ideal é utilizar o código 410 (Gone).",
  },
  {
    "status": 405,
    "legenda": "Method Not Allowed",
    "imagem": "status405",
    "descricao": "Indica que o verbo HTTP utilizado não é suportado, por exemplo: a requisição ocorre por meio de um get, porém o único método disponível é o post.Curiosidade: Existem um método chamado OPTIONS que retorna todos os verbos suportados naquela requisiçãoobs: ele também pode não ser permitido.",
  },
  {
    "status": 406,
    "legenda": "Not Acceptable",
    "imagem": "status406",
    "descricao": "indica que o servidor não pode produzir uma resposta que combine com a lista de valores aceitáveis definidas nos cabeçalhos de negociação de conteúdo da requisição proativa, e o servidor é incapaz de produzir uma representação padrão. Negociação de conteúdo proativa incluem: Accept, Accept-Charset, Accept-Encoding, Accept-Language.",
    "adicional": "Na prática, esse erro é raramente usado. Ao invés de responder usando esse código de erro, o que poderia ser enigmático ao usuário final e difícil de arrumar, servidores ignoram o cabeçalho e servem a página atual ao usuário. Se assume que mesmo que o usuário não fique completamente feliz, ele irá preferir isso ao invés do código de erro. Se o servidor retornar este status de erro, o corpo da mensagem deve conter a a lista disponíveis de representações do recurso, possibilitando ao usuário escolher entre elas.",
  },
  {
    "status": 407,
    "legenda": "Proxy Authentication Required",
    "imagem": "status407",
    "descricao": "Indica um erro do lado cliente, informando que uma solicitação não está sendo bem aplicada. Isso ocorre porque falta a validar as credencias de autenticação para um proxy server que intermedia o navegador e o servidor que pode acessar o recurso solicitado. Este erro é enviado com um cabeçalho Proxy-Authenticate que contém informações de como fazer uma autorização correta.",
  },
  {
    "status": 408,
    "legenda": "Request Timeout",
    "imagem": "status408",
    "descricao": "Significa que o servidor irá encerrar essa conexão em desuso. É enviado a uma conexão parada por alguns servidores, mesmo sem nenhuma requisição feita anteriormente pelo cliente. O servidor deve enviar no cabeçalho de resposta 'close' Connection já que 408 implica que o servidor decidiu encerrar a conexão ao invés de continuar aguardando.",
  },
  {
    "status": 409,
    "legenda": "Conflict",
    "imagem": "status409",
    "descricao": "Indica que a solicitação atual conflitou com o recurso que está no servidor. Conflitos são mais frequentes quando usado o método PUT. Por exemplo, você pode receber uma resposta 409 quando fizer upload de um arquivo que é mais antigo do que já existe no servidor, resultando em conflito de versão.",
    "adicional": "O servidor deve gerar um payload que inclua informações suficientes para que um usuário reconheça a origem do conflito.",
  },
  {
    "status": 410,
    "legenda": "Gone",
    "imagem": "status410",
    "descricao": "Indica que o acesso ao recurso não está mais disponível no servidor de origem, e que esta condição tende a ser permanente. Se você não sabe se a ausência do recurso é temporária ou permanente, o código de status 404 deverá ser utilizado.",
    "adicional": "Uma resposta 410 response é armazenada em cache por default.",
  },
  {
    "status": 411,
    "legenda": "Length Required",
    "imagem": "status411",
    "descricao": "Indica que o servidor se nega a aceitar a requisição sem um cabeçalho Content-Length definido.",
    "adicional": "Quando são enviados dados em uma série de blocos, o cabeçalho Content-Length é omitido e no início de cada bloco você precisa adicionar o tamanho do bloco corrente no formato hexadecimal.",
  },
  {
    "status": 412,
    "legenda": "Precondition Failed",
    "imagem": "status412",
    "descricao": "Indica que o acesso ao recurso especificado foi negado. Isso acontece com requisições condicionais em métodos que não são GET ou HEAD quando a condição definida pelo cabeçalho If-Unmodified-Since ou If-None-Match não é satisfeita. Nesse caso, a requisição, geralmente um upload ou modificação de um recurso, não pode ser feita e o código de error de resposta é enviado de volta.",
  },
  {
    "status": 413,
    "legenda": "Content Too Large",
    "imagem": "status413",
    "descricao": "Indica que a carga da requisição é mais larga que os limites estabelecidos pelo servidor; o servidor pode encerrar a conexão ou retornar Retry-After no campo de cabeçalho.",
  },
  {
    "status": 414,
    "legenda": "URI Too Long",
    "imagem": "status414",
    "descricao": "Indica que o tamanho da URI requisitada pelo cliente é maior do que o tamanho que o servidor aceita interpretar.",
    "adicional": "Esta condição rara só é provável de ocorrer quando um cliente converteu indevidamente uma solicitação POST em uma solicitação GET com informações de consulta longas, quando o cliente caiu em um 'buraco negro' de redirecionamento (por exemplo, um prefixo URI redirecionado que aponta para um seu próprio sufixo) ou quando o servidor está sendo atacado por um cliente que tenta explorar brechas de segurança em potencial.",
  },
  {
    "status": 415,
    "legenda": "Unsupported Media Type",
    "imagem": "status415",
    "descricao": "Indica que o servidor se recusou a aceitar a requisição porque o formato do payload não é um formato suportado. O problema do formato pode ter ocorrido pelos valores indicados no Content-Type ou Content-Encoding, ou pelo resultado da inspeção do dado em si.",
  },
  {
    "status": 416,
    "legenda": "Range Not Satisfiable",
    "imagem": "status416",
    "descricao": "Indica que o servidor não pode servir as sequências solicitadas. A razão mais provável é que o documento não contenha tais sequências, ou que o valor do cabeçalho Range, apesar de sintaticamente correto, não faça sentido. A mensagem de resposta 416 contém um cabeçalho Content-Range indicando uma sequência insatisfatória (que é um '*') seguido por uma '/' e o tamanho atual do recurso. E.g. Content-Range: bytes */12777.",
    "adicional": "Observando este erro, os navegadores geralmente, ou abortam a operação (por exemplo, o download será considerado não recuperável) ou requisitar o documento inteiro novamente.",
  },
  {
    "status": 417,
    "legenda": "Expectation Failed",
    "imagem": "status417",
    "descricao": "Indica que a expectativa enviada no cabeçalho da requisição Expect não foi suprida.",
  },
  {
    "status": 418,
    "legenda": "I'm a teapot",
    "imagem": "status418",
    "descricao": "Indica que o servidor se recusa a preparar café por ser um bule de chá. Este erro é uma referência ao Hyper Text Coffee Pot Control Protocol, que foi uma piada de 1º de abril de 1998. Não é um código de status oficial e não está definido na RFC então não deveria ser usado em produção.",
    "adicional": "Não sendo uma especificação séria, várias bibliotecas e frameworks implementaram essa especificação como forma de continuar a piada. Alguns sites usam esta resposta para solicitações que não querem tratar, como consultas automatizadas.",
  },
  {
    "status": 421,
    "legenda": "Misdirected Request",
    "imagem": "status421",
    "descricao": "Indica que a solicitação foi direcionada para um servidor que não é capaz de produzir uma resposta. Isso pode ser enviado por um servidor que não está configurado para produzir respostas para a combinação de esquema e autoridade que estão incluídas no URI de solicitação. Os clientes podem tentar novamente a solicitação por uma conexão diferente.",
    "adicional": "Este código de status não deve ser gerado por proxies.",
  },
  {
    "status": 422,
    "legenda": "Unprocessable Content",
    "imagem": "status422",
    "descricao": "Indica que o servidor entende o tipo de conteúdo da entidade da requisição, e a sintaxe da requisição esta correta, mas não foi possível processar as instruções presentes.",
    "adicional": "Por exemplo, essa condição de erro pode ocorrer se um corpo de solicitação XML contiver instruções XML bem formadas (ou seja, sintaticamente corretas), mas semanticamente erradas. O cliente não deve repetir esta requisição sem modificações.",
  },
  {
    "status": 423,
    "legenda": "Locked",
    "imagem": "status423",
    "descricao": "Indica que um recurso está bloqueado, o que significa que não pode ser acessado. Seu corpo de resposta deve conter informações no formato XML do WebDAV.",
    "adicional": "Nota: A capacidade de bloquear um recurso para evitar conflitos é específica para alguns servidores WebDAV. Os navegadores que acessam páginas da web nunca encontrarão esse código de status; nos casos errôneos em que acontece, eles lidarão com isso como um genérico 400Código de estado.",
  },
  {
    "status": 424,
    "legenda": "Failed Dependency",
    "imagem": "status424",
    "descricao": "Indica que o método não pôde ser executado no recurso porque a ação solicitada dependia de outra ação e essa ação falhou. Servidores web regulares normalmente não retornam esse código de status, mas alguns protocolos como o WebDAV podem devolvê-lo. Por exemplo, no WebDAV, se um PROPPATCH solicitação foi emitida, e um comando falha, em seguida, automaticamente todos os outros comandos também falharão.",
  },
  {
    "status": 425,
    "legenda": "Too Early",
    "imagem": "status425",
    "descricao": "Indica que o servidor não quer correr o risco de processar uma requisição que pode ser repetida, o que cria um potencial risco para ataques de repetição.",
    "adicional": "Esta é uma tecnologia experimental. Verifique a tabela de compatibilidade entre navegadores cuidadosamente antes de usar essa funcionalidade em produção.",
  },
  {
    "status": 426,
    "legenda": "Upgrade Required",
    "imagem": "status426",
    "descricao": "Indica que o servidor recusa o processamento da requisição usando o protocolo atual mas poderá ser processado caso o cliente atualize para um protocolo diferente. O servidor envia uma header Upgrade com esta resposta para indicar qual o protocolo necessário.",
    "adicional": "",
  },
  {
    "status": 428,
    "legenda": "Precondition Required",
    "imagem": "status428",
    "descricao": "Indica que o servidor precisa que a requisição seja condicional. Normalmente, isto significa que um cabeçalho pré-requisito, como o If-Match, está faltando. Quando o cabeçalho pré-requisito não é o mesmo esperado pelo servidor, a resposta deve ser 412 Precondition Failed.",
  },
  {
    "status": 429,
    "legenda": "Too Many Requests",
    "imagem": "status429",
    "descricao": "Indica que o usuário enviou muitos pedidos em um determinado período de tempo. Um header Retry-After pode ser incluído na resposta indicando quanto tempo o usuário deve esperar antes de fazer um novo pedido.",
    "adicional": "Observe que esta especificação não define como o servidor de origem identifica o usuário, nem como conta as solicitações. Por exemplo, um servidor de origem que está limitando as taxas de solicitação pode fazer isso com base nas contagens de solicitações por recurso, em todo o servidor ou mesmo entre um conjunto de servidores. Da mesma forma, ele pode identificar o usuário por suas credenciais de autenticação ou um cookie com estado. Respostas com o código de status 429 não devem ser armazenadas por um cache.",
  },
  {
    "status": 431,
    "legenda": "Request Header Fields Too Large",
    "imagem": "status431",
    "descricao": "Indica que o servidor se recusou a processar a requisição por que os cabeçalhos HTTP da mesma são muito grandes. A requisição pode ser resubmetida depois de o tamanho dos cabeçalhos serem reduzidos. Servidores vão produzir esse status frequentemente se o cabeçalho Referer URL é muito longo ou existem muitos Cookies sendo enviados na requisição",
    "adicional": "Ele pode ser usado quando o conjunto de campos de cabeçalho de solicitação no total é muito grande e quando um único campo de cabeçalho está em falta. No último caso, a representação da resposta deve especificar qual campo de cabeçalho é muito grande. ",
  },
  {
    "status": 451,
    "legenda": "Unavailable For Legal Reasons",
    "imagem": "status451",
    "descricao": "Indica que o recurso solicitado pelo usuário não está disponível por motivos legais, como em uma página web para a qual foi emitida uma ação legal. As respostas que usam este código de status devem incluir uma explicação, no corpo da resposta, dos detalhes da demanda legal: a parte que a faz, a legislação ou regulamento aplicável e a que classes de pessoa e recursos se aplica.",
    "adicional": "A utilização do código de status 451 não implica na existência ou inexistência do recurso nomeado na solicitação. Ou seja, é possível que, caso as demandas judiciais sejam retiradas, a solicitação do recurso ainda não seja bem-sucedida. Observe que, em muitos casos, os clientes ainda podem acessar o recurso negado usando contramedidas técnicas, como uma VPN ou a rede Tor.",
  },
  {
    "status": 500,
    "legenda": "Internal Server Error",
    "imagem": "status500",
    "descricao": "Indica que encontrou uma condição inesperada e que o impediu de atender à solicitação. Essa resposta de erro é uma resposta genérica 'abrangente'. Às vezes, os arquivos log de servidores podem responder com um status code 500 acompanhado de mais detalhes sobre o request para evitar que no futuro erros desse tipo possam voltar a acontecer.",
  },
  {
    "status": 501,
    "legenda": "Not Implemented",
    "imagem": "status501",
    "descricao": "Indica que o servidor não suporta a funcionalidade requerida para completar a requisição. Esta é a resposta apropriada para quando o servidor não reconhece o método requisitado e não tem capacidade de suporta-lo para nenhum recurso. Os únicos métodos de requisição que os servidores suportam obrigatóriamente ( e, portanto, isso não deve retornar este código) são GET e HEAD.",
    "adicional": "Uma resposta 501 é cacheada por padrão, ou seja, a menos que os cabeçalhos de cache indiquem outra forma.",
  },
  {
    "status": 502,
    "legenda": "Bad Gateway",
    "imagem": "status502",
    "descricao": "Retornado pelo servidor indica que ele, enquanto atuando como um servidor intermediário (gateway ou proxy), recebeu uma resposta inválida do servidor para o qual a requisição foi encaminhada (upstream server).",
    "adicional": "Um erro 502 geralmente não é algo que você possa corrigir, mas requer uma correção por parte do servidor web ou dos proxies através dos quais você está tentando obter acesso.",
  },
  {
    "status": 503,
    "legenda": "Service Unavailable",
    "imagem": "status503",
    "descricao": "Indica que o servidor não está pronto para lidar com a requisição. Causas comuns são um servidor que está em manutenção ou sobrecarregado. Esta resposta deve ser usada para condições temporárias, e o cabeçalho HTTP Retry-After deve, se possível, conter o tempo estimado para restabelecimento do serviço.",
    "adicional": "Juntamente com esta resposta deve ser enviada uma página de fácil compreensão para explicar o problema. Tal resposta não deve ser armazenada em cache.",
  },
  {
    "status": 504,
    "legenda": "Gateway Timeout",
    "imagem": "status504",
    "descricao": "Indica que o servidor, enquanto atuando como gateway ou proxy, não conseguiu responder em tempo. Um Gateway pode referir-se a diferentes elementos de rede e um erro 504 geralmente é algo que você não pode consertar, mas solicitar uma correção no servidor web ou proxy no qual você está tentando acessar.",
  },
  {
    "status": 505,
    "legenda": "HTTP Version Not Supported",
    "imagem": "status505",
    "descricao": "Indica que a versão HTTP utilizada na requisição não é suportada pelo servidor.",
  },
  {
    "status": 506,
    "legenda": "Variant Also Negotiates",
    "imagem": "status506",
    "descricao": "Pode ser dado no contexto de Negociação de Conteúdo Transparente (Transparent Content Negotiation). Esse protocolo permite ao cliente requerer a melhor variante de um dado recurso, onde um servidor fornece múltiplos variantes. O código de status Variant Also Negotiates indica um erro na configuração interna do servidor na qual a variante escolhida é em si configurada para entrar em uma negociação de conteúdo, então não é um endpoint de negociação apropriado.",
  },
  {
    "status": 507,
    "legenda": "Insufficient Storage",
    "imagem": "status507",
    "descricao": "Pode ser usado no contexto do protocolo Web Distributed Authoring and Versioning (WebDAV). Isso indica que o método não pode ser executado porque o servidor não pode salvar a representação necessária para completar a requisição com sucesso.",
    "adicional": "Esta condição é considerada temporária. Se a solicitação que recebeu este código de status foi o resultado de uma ação do usuário, a solicitação não deve ser repetida até que seja solicitada por uma ação do usuário separada.",
  },
  {
    "status": 508,
    "legenda": "Loop Detected",
    "imagem": "status508",
    "descricao": "Pode ser retornado em um contexto do protocolo Web Distributed Authoring and Versioning (WebDAV). Indica que o servidor finalizou uma operação porque encontrou um loop infinito enquando processava a requisição com 'Depth: infinity'. Esse código indica que toda a operação falhou.",
  },
  {
    "status": 510,
    "legenda": "Not Extended",
    "imagem": "status510",
    "descricao": "É enviado no contexto do HTTP Extension Framework. Na especificação, um cliente pode mandar uma requisição que contenha uma declaração de extensão, que descreve a extensão a ser utilizada. Se o servidor aceitar tal requisição, mas quaisquer extensões descritas na requisição não forem suportadas, o servidor então retorna uma resposta com o código de status 510. A requisição requer extensões adicionais para ser processada corretamente.",
  },
  {
    "status": 511,
    "legenda": "Network Authentication Required",
    "imagem": "status511",
    "descricao": "O cliente precisa realizar uma autenticação para utilizar a rede. Esse status não é gerado pelos servidores de origem, mas pela interceptação de proxies que controlam o acesso à rede. Às vezes, as operadoras de rede exigem alguma autenticação, aceitação de termos ou outra interação do usuário antes de conceder acesso (por exemplo, em um cyber café ou em um aeroporto). Eles geralmente identificam clientes que não o fizeram usando seus endereços de Controle de Acesso à Mídia(MAC)",
    "adicional": "As respostas com o código de status 511 não devem ser armazenadas por um cache.",
  }
];

  
export default statusCodes;
  